var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){a!=Array.prototype&&a!=Object.prototype&&(a[b]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,e,c){if(b){e=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];f in e||(e[f]={});e=e[f]}a=a[a.length-1];c=e[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,e,c){var b=this.length||0;0>e&&(e=Math.max(0,b+e));if(null==c||c>b)c=b;c=Number(c);0>c&&(c=Math.max(0,b+c));for(e=Number(e||0);e<c;e++)this[e]=a;return this}},"es6-impl","es3");
var string={game_config_error:"Game not properly configured. Check your configuration file.",game_mode_label:"Scenario :",game_mode:["Skirmish","Classic","Interception","Breakthrough","Convoy"],currenlt_stage:"Current Stage",ship_placement_remaining:"Remaining ship",ship_classes:["Battleship","Aircraft Carrier","Cruiser","Destroyer","Transport"],pending:"Pending...",rotate:"Rotate ship",assemble_fleet:"Assemble Fleet",start_battle:"Start Battle!",no_ship_prompt:"You cannot enter a battle with a ghost fleet!",
no_ap_prompt:"You must bring all your transport ships with you!",surrender:"Surrender your ships",game_objective_label:"Objective : ",game_objective_loading:"Waiting for briefing",game_objective_standard:"Destroy all enemy vessels",game_objective_intercept_bb:"Destroy enemy battleships",game_objective_intercept_cv:"Destroy enemy aircraft carriers",game_objective_breakthrough_bb:"Protect your battleships to break through enemy resistance",game_objective_breakthrough_cv:"Protect your aircraft carriers to break through enemy resistance",
game_objective_breakthrough:"Break through enemy resistance",game_objective_convoy:"Escort the transport ships to their destination",game_stage_aerial:"AERIAL COMBAT",game_stage_artillery:"FLEET ACTION",form_of_engagement_label:"Form of Engagement",form_of_engagement:["Parallel","Head On","T - Advantage","T - Disadvantage"],turn_counter_label:"Time Remaining: ",attack_remaining:"Attack Remaining",surrender_confirm:"Are you sure you want to surrender your ships? You will be treated as defeated!",victory:"VICTORY",
victory_description_standard:"All enemy vessels destroyed!",victory_description_intercept:"Target vessel destroyed!",victory_description_breakthrough:"You have arrived at your destination.",victory_description_convoy:"The transport ships have arrived at their destination.",defeat:"DEFEAT",defeat_description_standard:"Your fleet was annihilated.",defeat_description_intercept:"The enemy had reached their destination.",defeat_description_breakthrough:"You failed to protect your ships.",defeat_description_convoy:"The transport ships are destroyed.",
new_game:"Proceed into next battle",new_game_confirm:"Are you sure you want to start a new battle?",action_prompt_player:"Awaiting Orders",action_prompt_enemy:"INCOMING",ready:"Ready",tutorial_confirm:"Greetings commander.<br>It seems that this is the first time you get hold of a fleet.<br>Would you like to read the manual first?",tutorial_confirm_yes:"Of course.",tutorial_confirm_no:"No, thanks.",version_code:"Version 0.8.0",github_link_text:"Source code, guides and other materials are available on",
game_title:"Warships: Line of Battle"},img_url={crosshair:"img/tiles/crosshair.png",ship_icons:[["img/ships/jp/BB.png","img/ships/jp/CV.png","img/ships/jp/CA.png","img/ships/jp/DD.png","img/ships/jp/AP.svg"],["img/ships/us/BB.png","img/ships/us/CV.png","img/ships/us/CA.png","img/ships/us/DD.png","img/ships/us/AP.svg"],["img/ships/uk/BB.png","img/ships/uk/CV.png","img/ships/uk/CA.png","img/ships/uk/DD.png","img/ships/uk/AP.svg"],["img/ships/de/BB.png","img/ships/de/CV.png","img/ships/de/CA.png","img/ships/de/DD.png",
"img/ships/de/AP.svg"]],ship_tiles:[[["img/tiles/BB/sector_1_normal.png","img/tiles/BB/sector_2_normal.png","img/tiles/BB/sector_3_normal.png","img/tiles/BB/sector_4_normal.png"],["img/tiles/BB/sector_1_hit.png","img/tiles/BB/sector_2_hit.png","img/tiles/BB/sector_3_hit.png","img/tiles/BB/sector_4_hit.png"],["img/tiles/BB/sector_1_sunk.png","img/tiles/BB/sector_2_sunk.png","img/tiles/BB/sector_3_sunk.png","img/tiles/BB/sector_4_sunk.png"]],[["img/tiles/CV/sector_1_normal.png","img/tiles/CV/sector_2_normal.png",
"img/tiles/CV/sector_3_normal.png","img/tiles/CV/sector_4_normal.png"],["img/tiles/CV/sector_1_hit.png","img/tiles/CV/sector_2_hit.png","img/tiles/CV/sector_3_hit.png","img/tiles/CV/sector_4_hit.png"],["img/tiles/CV/sector_1_sunk.png","img/tiles/CV/sector_2_sunk.png","img/tiles/CV/sector_3_sunk.png","img/tiles/CV/sector_4_sunk.png"]],[["img/tiles/CA/sector_1_normal.png","img/tiles/CA/sector_2_normal.png","img/tiles/CA/sector_3_normal.png"],["img/tiles/CA/sector_1_hit.png","img/tiles/CA/sector_2_hit.png",
"img/tiles/CA/sector_3_hit.png"],["img/tiles/CA/sector_1_sunk.png","img/tiles/CA/sector_2_sunk.png","img/tiles/CA/sector_3_sunk.png"]],[["img/tiles/DD/sector_1_normal.png","img/tiles/DD/sector_2_normal.png"],["img/tiles/DD/sector_1_hit.png","img/tiles/DD/sector_2_hit.png"],["img/tiles/DD/sector_1_sunk.png","img/tiles/DD/sector_2_sunk.png"]],[["img/tiles/AP/sector_1_normal.png","img/tiles/AP/sector_2_normal.png","img/tiles/AP/sector_3_normal.png"],["img/tiles/AP/sector_1_hit.png","img/tiles/AP/sector_2_hit.png",
"img/tiles/AP/sector_3_hit.png"],["img/tiles/AP/sector_1_sunk.png","img/tiles/AP/sector_2_sunk.png","img/tiles/AP/sector_3_sunk.png"]]]},sfx_url={gun_fire:"sound/sfx/gunfire.ogg",explosion:"sound/sfx/explosion.ogg",plane_attack:"sound/sfx/plane.ogg",explosion_water:"sound/sfx/explosion-water.ogg",explosion_distant:"sound/sfx/explosion-distant.ogg"};function RNG(a,b){return Math.floor(Math.random()*(b-a+1))+a}function onConfigError(){alert(string.game_config_error);location.reload()}
var game_mode=0,GAME_MODE_SKIRMISH=0,GAME_MODE_CLASSIC=1,GAME_MODE_INTERCEPT=2,GAME_MODE_BREAKTHROUGH=3,GAME_MODE_CONVOY=4;
function showStartGameSetting(){document.getElementById("settingBox");for(i=0;i<string.game_mode.length;i++){var a=document.createElement("option");a.value=i;a.text=string.game_mode[i];document.getElementById("modeSelect").add(a)}document.getElementById("modeSelect").onchange=function(){onSelectedModeChanged()};a=document.getElementById("gameSetButton");a.innerHTML=string.ready;a.addEventListener("click",function(){document.getElementById("diff-easy").checked?ai_config=AI_CONFIGURATION_BASIC:document.getElementById("diff-normal").checked&&
(ai_config=AI_CONFIGURATION_INTERMEDIATE);RANDOM_MAP_SIZE=document.getElementById("randomMap").checked?!0:!1;SOUND_ENABLED=document.getElementById("sound").checked?!0:!1;readyGame()},!1)}
function onSelectedModeChanged(){var a=document.getElementById("modeSelect");switch(parseInt(a.options[a.selectedIndex].value)){case GAME_MODE_SKIRMISH:game_mode=GAME_MODE_SKIRMISH;document.getElementById("randomMap").disabled=!1;break;case GAME_MODE_INTERCEPT:game_mode=GAME_MODE_INTERCEPT;document.getElementById("randomMap").disabled=!1;break;case GAME_MODE_BREAKTHROUGH:game_mode=GAME_MODE_BREAKTHROUGH;document.getElementById("randomMap").disabled=!1;break;case GAME_MODE_CONVOY:game_mode=GAME_MODE_CONVOY;
document.getElementById("randomMap").disabled=!1;break;case GAME_MODE_CLASSIC:game_mode=GAME_MODE_CLASSIC,document.getElementById("randomMap").disabled=!0,RANDOM_MAP_SIZE=!1}}function openTutorial(){window.open("https://github.com/tonY1883/fleet-battle/wiki/Basic-Tutorial","_blank")}
window.onload=function(){750>screen.width?window.location="mobile.htm":(document.getElementById("title").innerHTML=string.game_title,document.title=string.game_title,document.getElementById("version-code").innerHTML=string.version_code,document.getElementById("github-link").innerHTML=string.github_link_text,null===localStorage.getItem("isPlaying")&&(localStorage.setItem("isPlaying","yes"),document.getElementById("confirm-text").innerHTML=string.tutorial_confirm,document.getElementById("yes-btn").innerHTML=
string.tutorial_confirm_yes,document.getElementById("yes-btn").addEventListener("click",function(){openTutorial();document.getElementById("tutorialBox").style.display="none"},!1),document.getElementById("no-btn").innerHTML=string.tutorial_confirm_no,document.getElementById("no-btn").addEventListener("click",function(){document.getElementById("tutorialBox").style.display="none"},!1),document.getElementById("tutorialBox").style.display="table"),showStartGameSetting())};
var AI_CONFIGURATION_BASIC=0,AI_CONFIGURATION_INTERMEDIATE=1,AI_CONFIGURATION_ADVANCED=2,AI_CONFIGURATION_ALL_SEEING=3;function shipPlacementMain(){switch(ai_config){case AI_CONFIGURATION_BASIC:shipPlacementBasic();break;case AI_CONFIGURATION_INTERMEDIATE:shipPlacementIntermediate();break;case AI_CONFIGURATION_ADVANCED:shipPlacementAdvanced();break;case AI_CONFIGURATION_ALL_SEEING:shipPlacementAdvanced();break;default:onConfigError()}}var ship_size;
function shipPlacableAi(a,b,e,c){if(e==SHIP_CLASS_BB&&player_2_ships_count[SHIP_CLASS_BB]>=max_bb_count||e==SHIP_CLASS_CV&&player_2_ships_count[SHIP_CLASS_CV]>=max_cv_count||e==SHIP_CLASS_CA&&player_2_ships_count[SHIP_CLASS_CA]>=max_ca_count||e==SHIP_CLASS_DD&&player_2_ships_count[SHIP_CLASS_DD]>=max_dd_count)return!1;switch(e){case SHIP_CLASS_BB:case SHIP_CLASS_CV:ship_size=4;break;case SHIP_CLASS_CA:ship_size=3;break;case SHIP_CLASS_DD:ship_size=2}if(c==SHIP_COURSE_VERTICAL){if(a+ship_size<map_size&&
b<map_size){for(e=0;e<ship_size;e++)if(document.getElementById("monitorRight").querySelector("[x='"+(a+e)+"'][y='"+b+"']").hasAttribute("placed"))return!1;return!0}return!1}if(c==SHIP_COURSE_HORIZONTAL){if(b+ship_size<map_size&&a<map_size){for(e=0;e<ship_size;e++)if(document.getElementById("monitorRight").querySelector("[y='"+(b+e)+"'][x='"+a+"']").hasAttribute("placed"))return!1;return!0}return!1}}
function shipPlacementBasic(){var a=RNG(0,map_size),b=RNG(0,map_size),e=RNG(SHIP_COURSE_VERTICAL,SHIP_COURSE_HORIZONTAL),c=RNG(SHIP_CLASS_BB,SHIP_CLASS_DD);if(shipPlacableAi(a,b,c,e)){if(e==SHIP_COURSE_VERTICAL)for(var f=0;f<ship_size;f++){var g=document.getElementById("monitorRight").querySelector("[x='"+(a+f)+"'][y='"+b+"']");g.setAttribute("placed","true");g.setAttribute("ship-class",c);g.setAttribute("head-x",a);g.setAttribute("head-y",b);g.setAttribute("ship-bearing",e);g.setAttribute("sector",
f);if(!FOG_OF_WAR){g.style.backgroundImage="url('"+img_url.ship_tiles[c][0][f]+"')";var h=g.getAttribute("class");h+=" ShipsTile";g.setAttribute("class",h)}}else if(e==SHIP_COURSE_HORIZONTAL)for(f=0;f<ship_size;f++)g=document.getElementById("monitorRight").querySelector("[y='"+(b+f)+"'][x='"+a+"']"),g.setAttribute("placed","true"),g.setAttribute("ship-class",c),g.setAttribute("head-x",a),g.setAttribute("head-y",b),g.setAttribute("ship-bearing",e),g.setAttribute("sector",f),FOG_OF_WAR||(g.style.backgroundImage=
"url('"+img_url.ship_tiles[c][0][f]+"')",h=g.getAttribute("class"),h+=" ShipsTileHorizontal",g.setAttribute("class",h));player_2_fleet_course+=e;switch(c){case SHIP_CLASS_BB:player_2_ships_count[SHIP_CLASS_BB]+=1;break;case SHIP_CLASS_CV:player_2_ships_count[SHIP_CLASS_CV]+=1;break;case SHIP_CLASS_CA:player_2_ships_count[SHIP_CLASS_CA]+=1;break;case SHIP_CLASS_DD:player_2_ships_count[SHIP_CLASS_DD]+=1}}getPlayerShipCount(PLAYER_2)>=max_ship_count||shipPlacementBasic()}var q=0;
function shipPlacementIntermediate(){switch(q){case 0:var a=RNG(0,Math.round(map_size/2));var b=RNG(0,Math.round(map_size/2));break;case 1:a=RNG(Math.round(map_size/2),map_size);b=RNG(0,Math.round(map_size/2));break;case 2:a=RNG(0,Math.round(map_size/2));b=RNG(Math.round(map_size/2),map_size);break;case 3:a=RNG(Math.round(map_size/2),map_size),b=RNG(Math.round(map_size/2),map_size)}var e=RNG(SHIP_COURSE_VERTICAL,SHIP_COURSE_HORIZONTAL),c=RNG(SHIP_CLASS_BB,SHIP_CLASS_DD);if(shipPlacableAi(a,b,c,e)){if(e==
SHIP_COURSE_VERTICAL)for(var f=0;f<ship_size;f++){var g=document.getElementById("monitorRight").querySelector("[x='"+(a+f)+"'][y='"+b+"']");g.setAttribute("placed","true");g.setAttribute("ship-class",c);g.setAttribute("head-x",a);g.setAttribute("head-y",b);g.setAttribute("ship-bearing",e);g.setAttribute("sector",f);if(!FOG_OF_WAR){g.style.backgroundImage="url('"+img_url.ship_tiles[c][0][f]+"')";var h=g.getAttribute("class");h+=" ShipsTile";g.setAttribute("class",h)}}else if(e==SHIP_COURSE_HORIZONTAL)for(f=
0;f<ship_size;f++)g=document.getElementById("monitorRight").querySelector("[y='"+(b+f)+"'][x='"+a+"']"),g.setAttribute("placed","true"),g.setAttribute("ship-class",c),g.setAttribute("head-x",a),g.setAttribute("head-y",b),g.setAttribute("ship-bearing",e),g.setAttribute("sector",f),FOG_OF_WAR||(g.style.backgroundImage="url('"+img_url.ship_tiles[c][0][f]+"')",h=g.getAttribute("class"),h+=" ShipsTileHorizontal",g.setAttribute("class",h));player_2_fleet_course+=e;switch(c){case SHIP_CLASS_BB:player_2_ships_count[SHIP_CLASS_BB]+=
1;break;case SHIP_CLASS_CV:player_2_ships_count[SHIP_CLASS_CV]+=1;break;case SHIP_CLASS_CA:player_2_ships_count[SHIP_CLASS_CA]+=1;break;case SHIP_CLASS_DD:player_2_ships_count[SHIP_CLASS_DD]+=1}q+=1;3<q&&(q=0)}getPlayerShipCount(PLAYER_2)>=max_ship_count||shipPlacementIntermediate()}
function shipPlacementAdvanced(){switch(q){case 0:var a=RNG(0,Math.round(map_size/2));var b=RNG(0,Math.round(map_size/2));break;case 1:a=RNG(Math.round(map_size/2),map_size);b=RNG(0,Math.round(map_size/2));break;case 2:a=RNG(0,Math.round(map_size/2));b=RNG(Math.round(map_size/2),map_size);break;case 3:a=RNG(Math.round(map_size/2),map_size),b=RNG(Math.round(map_size/2),map_size)}var e=RNG(SHIP_COURSE_VERTICAL,SHIP_COURSE_HORIZONTAL);var c=player_2_ships_count[SHIP_CLASS_CV]<max_cv_count?SHIP_CLASS_CV:
player_2_ships_count[SHIP_CLASS_BB]<max_bb_count&&player_2_ships_count[SHIP_CLASS_BB]<Math.round(max_ship_count/2)?SHIP_CLASS_BB:RNG(SHIP_CLASS_CA,SHIP_CLASS_DD);if(shipPlacableAi(a,b,c,e)){if(e==SHIP_COURSE_VERTICAL)for(var f=0;f<ship_size;f++){var g=document.getElementById("monitorRight").querySelector("[x='"+(a+f)+"'][y='"+b+"']");g.setAttribute("placed","true");g.setAttribute("ship-class",c);g.setAttribute("head-x",a);g.setAttribute("head-y",b);g.setAttribute("ship-bearing",e);g.setAttribute("sector",
f);if(!FOG_OF_WAR){g.style.backgroundImage="url('"+img_url.ship_tiles[c][0][f]+"')";var h=g.getAttribute("class");h+=" ShipsTile";g.setAttribute("class",h)}}else if(e==SHIP_COURSE_HORIZONTAL)for(f=0;f<ship_size;f++)g=document.getElementById("monitorRight").querySelector("[y='"+(b+f)+"'][x='"+a+"']"),g.setAttribute("placed","true"),g.setAttribute("ship-class",c),g.setAttribute("head-x",a),g.setAttribute("head-y",b),g.setAttribute("ship-bearing",e),g.setAttribute("sector",f),FOG_OF_WAR||(g.style.backgroundImage=
"url('"+img_url.ship_tiles[c][0][f]+"')",h=g.getAttribute("class"),h+=" ShipsTileHorizontal",g.setAttribute("class",h));player_2_fleet_course+=e;switch(c){case SHIP_CLASS_BB:player_2_ships_count[SHIP_CLASS_BB]+=1;break;case SHIP_CLASS_CV:player_2_ships_count[SHIP_CLASS_CV]+=1;break;case SHIP_CLASS_CA:player_2_ships_count[SHIP_CLASS_CA]+=1;break;case SHIP_CLASS_DD:player_2_ships_count[SHIP_CLASS_DD]+=1}q+=1;3<q&&(q=0)}getPlayerShipCount(PLAYER_2)>=max_ship_count||shipPlacementAdvanced()}
function attackMain(){switch(ai_config){case AI_CONFIGURATION_BASIC:attackBasic();break;case AI_CONFIGURATION_INTERMEDIATE:attackIntermediate();break;case AI_CONFIGURATION_ADVANCED:attackAdvanced();break;case AI_CONFIGURATION_ALL_SEEING:attackAllSeeing();break;default:onConfigError()}}var lastHitCoorX,lastHitCoorY,lastHit=!1,lastLastHit=!1,d=0,x,y;
function attackBasic(){if(lastHit)switch(lastLastHit||(d=RNG(0,3)),d){case 0:x=null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX+1)+"']")?lastHitCoorX+1:lastHitCoorX-1;y=lastHitCoorY;break;case 1:x=null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX-1)+"']")?lastHitCoorX-1:lastHitCoorX+1;y=lastHitCoorY;break;case 2:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY-1)+
"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY-1,x=lastHitCoorX):(x=lastHitCoorX,y=lastHitCoorY+1);break;case 3:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY+1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY+1,x=lastHitCoorX):(x=lastHitCoorX,y=lastHitCoorY-1)}else x=RNG(0,map_size),y=RNG(0,map_size);var a=document.getElementById("monitorLeft").querySelector("[y='"+y+"'][x='"+x+"']");null==a||a.hasAttribute("sunk")?(lastHit=!1,attackBasic()):(lastLastHit=lastHit,--player_2_attack_count,
ship_class_acting==SHIP_CLASS_CV?airStrike(x,y):artilleryStrike(x,y))}var target_locked=!1,lockedCoorX,lockedCoorY,hitCount=0;
function attackIntermediate(){if(target_locked)if(lastHit)switch(!lastLastHit&&2>hitCount&&(d=RNG(0,3)),d){case 0:null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX+1)+"']")?x=lastHitCoorX+1:(d=1,x=lastHitCoorX-1);y=lastHitCoorY;break;case 1:null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX-1)+"']")?x=lastHitCoorX-1:(d=0,x=lastHitCoorX+1);y=lastHitCoorY;break;case 2:null!=document.getElementById("monitorLeft").querySelector("[y='"+
(lastHitCoorY-1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY-1,x=lastHitCoorX):(d=3,x=lastHitCoorX,y=lastHitCoorY+1);break;case 3:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY+1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY+1,x=lastHitCoorX):(d=2,x=lastHitCoorX,y=lastHitCoorY-1)}else if(lastLastHit)if(2>hitCount)switch(d=RNG(0,3),d){case 0:null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX+1)+"']")?x=lastHitCoorX+
1:(d=1,x=lastHitCoorX-1);y=lastHitCoorY;break;case 1:null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX-1)+"']")?x=lastHitCoorX-1:(d=0,x=lastHitCoorX+1);y=lastHitCoorY;break;case 2:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY-1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY-1,x=lastHitCoorX):(d=3,x=lastHitCoorX,y=lastHitCoorY+1);break;case 3:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY+
1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY+1,x=lastHitCoorX):(d=2,x=lastHitCoorX,y=lastHitCoorY-1)}else if(4>hitCount)switch(d){case 0:null!=document.getElementById("monitorLeft").querySelector("[y='"+lockedCoorY+"'][x='"+(lockedCoorX-1)+"']")&&(x=lockedCoorX-1,y=lockedCoorY,d=1);break;case 1:null!=document.getElementById("monitorLeft").querySelector("[y='"+lockedCoorY+"'][x='"+(lockedCoorX+1)+"']")&&(x=lockedCoorX+1,y=lockedCoorY,d=0);break;case 2:null!=document.getElementById("monitorLeft").querySelector("[y='"+
(lockedCoorY+1)+"'][x='"+lockedCoorX+"']")&&(y=lockedCoorY+1,x=lockedCoorX,d=3);break;case 3:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lockedCoorY-1)+"'][x='"+lockedCoorX+"']")&&(y=lockedCoorY-1,x=lockedCoorX,d=2)}else switch(d){case 0:x=lastHitCoorX;y=lastHitCoorY;d=1;break;case 1:x=lastHitCoorX;y=lastHitCoorY;d=0;break;case 2:x=lastHitCoorX;y=lastHitCoorY;d=3;break;case 3:x=lastHitCoorX,y=lastHitCoorY,d=2}else if(lastHitCoorX==lockedCoorX&&lastHitCoorY==lockedCoorY)switch(d=
RNG(0,3),d){case 0:x=null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX+1)+"']")?lastHitCoorX+1:lastHitCoorX-1;y=lastHitCoorY;break;case 1:x=null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX-1)+"']")?lastHitCoorX-1:lastHitCoorX+1;y=lastHitCoorY;break;case 2:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY-1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY-1,x=lastHitCoorX):
(x=lastHitCoorX,y=lastHitCoorY+1);break;case 3:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY+1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY+1,x=lastHitCoorX):(x=lastHitCoorX,y=lastHitCoorY-1)}else x=RNG(0,map_size),y=RNG(0,map_size);else x=RNG(0,map_size),y=RNG(0,map_size);var a=document.getElementById("monitorLeft").querySelector("[y='"+y+"'][x='"+x+"']");null==a||a.hasAttribute("sunk")||!target_locked&&a.hasAttribute("hit")?attackIntermediate():(lastLastHit=lastHit,
--player_2_attack_count,ship_class_acting==SHIP_CLASS_CV?airStrike(x,y):artilleryStrike(x,y))}
function attackAdvanced(){if(target_locked)if(lastHit)switch(!lastLastHit&&2>hitCount&&(d=RNG(0,3)),d){case 0:null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX+1)+"']")?x=lastHitCoorX+1:(d=1,x=lastHitCoorX-1);y=lastHitCoorY;break;case 1:null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX-1)+"']")?x=lastHitCoorX-1:(d=0,x=lastHitCoorX+1);y=lastHitCoorY;break;case 2:null!=document.getElementById("monitorLeft").querySelector("[y='"+
(lastHitCoorY-1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY-1,x=lastHitCoorX):(d=3,x=lastHitCoorX,y=lastHitCoorY+1);break;case 3:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY+1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY+1,x=lastHitCoorX):(d=2,x=lastHitCoorX,y=lastHitCoorY-1)}else if(lastLastHit)if(2>hitCount)switch(d=RNG(0,3),d){case 0:null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX+1)+"']")?x=lastHitCoorX+
1:(d=1,x=lastHitCoorX-1);y=lastHitCoorY;break;case 1:null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX-1)+"']")?x=lastHitCoorX-1:(d=0,x=lastHitCoorX+1);y=lastHitCoorY;break;case 2:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY-1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY-1,x=lastHitCoorX):(d=3,x=lastHitCoorX,y=lastHitCoorY+1);break;case 3:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY+
1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY+1,x=lastHitCoorX):(d=2,x=lastHitCoorX,y=lastHitCoorY-1)}else if(4>hitCount)switch(d){case 0:null!=document.getElementById("monitorLeft").querySelector("[y='"+lockedCoorY+"'][x='"+(lockedCoorX-1)+"']")&&(x=lockedCoorX-1,y=lockedCoorY,d=1);break;case 1:null!=document.getElementById("monitorLeft").querySelector("[y='"+lockedCoorY+"'][x='"+(lockedCoorX+1)+"']")&&(x=lockedCoorX+1,y=lockedCoorY,d=0);break;case 2:null!=document.getElementById("monitorLeft").querySelector("[y='"+
(lockedCoorY+1)+"'][x='"+lockedCoorX+"']")&&(y=lockedCoorY+1,x=lockedCoorX,d=3);break;case 3:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lockedCoorY-1)+"'][x='"+lockedCoorX+"']")&&(y=lockedCoorY-1,x=lockedCoorX,d=2)}else switch(d){case 0:x=lastHitCoorX;y=lastHitCoorY;d=1;break;case 1:x=lastHitCoorX;y=lastHitCoorY;d=0;break;case 2:x=lastHitCoorX;y=lastHitCoorY;d=3;break;case 3:x=lastHitCoorX,y=lastHitCoorY,d=2}else if(lastHitCoorX==lockedCoorX&&lastHitCoorY==lockedCoorY)switch(d=
RNG(0,3),d){case 0:x=null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX+1)+"']")?lastHitCoorX+1:lastHitCoorX-1;y=lastHitCoorY;break;case 1:x=null!=document.getElementById("monitorLeft").querySelector("[y='"+lastHitCoorY+"'][x='"+(lastHitCoorX-1)+"']")?lastHitCoorX-1:lastHitCoorX+1;y=lastHitCoorY;break;case 2:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY-1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY-1,x=lastHitCoorX):
(x=lastHitCoorX,y=lastHitCoorY+1);break;case 3:null!=document.getElementById("monitorLeft").querySelector("[y='"+(lastHitCoorY+1)+"'][x='"+lastHitCoorX+"']")?(y=lastHitCoorY+1,x=lastHitCoorX):(x=lastHitCoorX,y=lastHitCoorY-1)}else{switch(q){case 0:x=RNG(0,Math.round(map_size/2));y=RNG(0,Math.round(map_size/2));break;case 1:x=RNG(Math.round(map_size/2),map_size);y=RNG(0,Math.round(map_size/2));break;case 2:x=RNG(0,Math.round(map_size/2));y=RNG(Math.round(map_size/2),map_size);break;case 3:x=RNG(Math.round(map_size/
2),map_size),y=RNG(Math.round(map_size/2),map_size)}q+=1;3<q&&(q=0)}else{switch(q){case 0:x=RNG(0,Math.round(map_size/2));y=RNG(0,Math.round(map_size/2));break;case 1:x=RNG(Math.round(map_size/2),map_size);y=RNG(0,Math.round(map_size/2));break;case 2:x=RNG(0,Math.round(map_size/2));y=RNG(Math.round(map_size/2),map_size);break;case 3:x=RNG(Math.round(map_size/2),map_size),y=RNG(Math.round(map_size/2),map_size)}q+=1;3<q&&(q=0)}var a=document.getElementById("monitorLeft").querySelector("[y='"+y+"'][x='"+
x+"']");null==a||a.hasAttribute("sunk")||!target_locked&&a.hasAttribute("hit")?attackIntermediate():(lastLastHit=lastHit,--player_2_attack_count,ship_class_acting==SHIP_CLASS_CV?airStrike(x,y):artilleryStrike(x,y))}
function attackAllSeeing(){var a=document.getElementById("monitorLeft").querySelectorAll("[placed='true']");var b=RNG(0,a.length-1);if(a[b].hasAttribute("sunk")||2<=parseInt(a[b].getAttribute("hit_count")))attackAllSeeing();else{var e=parseInt(a[b].getAttribute("x"));b=parseInt(a[b].getAttribute("y"));RNG(0,1);e=RNG(e-1,e);RNG(0,1);b=RNG(b,b+1);--player_2_attack_count;ship_class_acting==SHIP_CLASS_CV?airStrike(e,b):artilleryStrike(e,b)}}
function onAttackResult(a){lastHit=a;switch(ai_config){case AI_CONFIGURATION_BASIC:lastHit&&(lastHitCoorY=y,lastHitCoorX=x);break;case AI_CONFIGURATION_INTERMEDIATE:case AI_CONFIGURATION_ADVANCED:lastHit&&(lastHitCoorY=y,lastHitCoorX=x,hitCount+=1,target_locked||(target_locked=!0,lockedCoorY=y,lockedCoorX=x),shipDestroyed("monitorLeft",x,y)&&(target_locked=!1,hitCount=0));break;case AI_CONFIGURATION_ALL_SEEING:break;default:onConfigError()}}
var SOUND_ENABLED=!0,RANDOM_MAP_SIZE=!1,RANDOM_MAP_SIZE_MAX=20,RANDOM_MAP_SIZE_MIN=10,DEFAULT_MAP_SIZE=14,DEFAULT_GRID_SIZE=32,MAX_SHIP_COUNT_STANDARD=6,MAX_BB_COUNT_STANDARD=4,MAX_CV_COUNT_STANDARD=3,MAX_CA_COUNT_STANDARD=6,MAX_DD_COUNT_STANDARD=6,MAX_SHIP_COUNT_CLASSIC=10,MAX_BB_COUNT_CLASSIC=1,MAX_CV_COUNT_CLASSIC=2,MAX_CA_COUNT_CLASSIC=3,MAX_DD_COUNT_CLASSIC=4,MAX_TURN_INTERCEPT_DEFAULT=8,MAX_TURN_INTERCEPT_MIN=6,MAX_TURN_INTERCEPT_MAX=12,RANDOM_TIME_INTERCEPT_BREAKTHROUGH=!0,SPECIFIC_CLASS_INTERCEPT_BREAKTHROUGH=
!0,AP_COUNT_CONVOY=3,FOG_OF_WAR=!0,ai_config=AI_CONFIGURATION_INTERMEDIATE,BB_ATTACK_COUNT=[2,1,2,1],CA_ATTACK_COUNT=[1,1,1,0],DD_ATTACK_COUNT=[1,1,1,0],CV_ATTACK_COUNT=[1,1,1,1],counter_text_left,counter_label_left,counter_text_right,counter_label_right,game_phase=0,GAME_PHASE_SHIP_PLACEMENT=0,GAME_PAHSE_AERIAL_COMBAT=1,GAME_PHASE_COMBAT=2,grid_size,map_size,SHIP_COURSE_VERTICAL=0,SHIP_COURSE_HORIZONTAL=1,FLEET_SPEED_FAST=0,FLEET_SPEED_SLOW=1,ENGAGEMENT_FORM_PARALLEL=0,ENGAGEMENT_FORM_HEADON=1,ENGAGEMENT_FORM_T_ADV=
2,ENGAGEMENT_FORM_T_DIS=3,SHIP_CLASS_BB=0,SHIP_CLASS_CV=1,SHIP_CLASS_CA=2,SHIP_CLASS_DD=3,SHIP_CLASS_AP=4,max_ship_count,max_bb_count,max_cv_count,max_ca_count,max_dd_count,max_ap_count,ship_class_placing,ship_course_placing=0,ship_size_placing,ship_class_target,ship_class_acting,acting_player,PLAYER_1=0,PLAYER_2=1,player_1_first_act_complete=!1,player_2_first_act_complete=!1,total_turn_counter=0,max_turn_intercept_breakthrough,player_1_ship_set=0,player_1_ships_count=[0,0,0,0,0],player_1_fleet_course=
0,player_1_fleet_speed,player_1_engagement_form,player_1_attack_count,player_1_turn_counter=0,player_1_acted=!1,player_2_ship_set=0,player_2_ships_count=[0,0,0,0,0],player_2_fleet_course=0,player_2_fleet_speed,player_2_engagement_form,player_2_attack_count,player_2_turn_counter=0,player_2_acted=!1,gun_fire_sound,plane_attack_sound,attack_hit_sound,attack_miss_sound,attack_hit_sound_distant;
function readyGame(){var a;SOUND_ENABLED&&(gun_fire_sound=new Audio(sfx_url.gun_fire),plane_attack_sound=new Audio(sfx_url.plane_attack),attack_hit_sound=new Audio(sfx_url.explosion),attack_miss_sound=new Audio(sfx_url.explosion_water),attack_hit_sound_distant=new Audio(sfx_url.explosion_distant));document.getElementById("gameTitle").innerHTML=string.game_title;var b=document.querySelectorAll(".Monitor");game_mode==GAME_MODE_CLASSIC?(map_size=10,grid_size=Math.floor(DEFAULT_GRID_SIZE*DEFAULT_MAP_SIZE/
map_size)):RANDOM_MAP_SIZE?(map_size=RNG(RANDOM_MAP_SIZE_MIN,RANDOM_MAP_SIZE_MAX),grid_size=Math.floor(DEFAULT_GRID_SIZE*DEFAULT_MAP_SIZE/map_size)):(map_size=DEFAULT_MAP_SIZE,grid_size=DEFAULT_GRID_SIZE);if(game_mode==GAME_MODE_INTERCEPT||game_mode==GAME_MODE_BREAKTHROUGH||game_mode==GAME_MODE_CONVOY)max_turn_intercept_breakthrough=RANDOM_TIME_INTERCEPT_BREAKTHROUGH?RNG(MAX_TURN_INTERCEPT_MIN,MAX_TURN_INTERCEPT_MAX):MAX_TURN_INTERCEPT_DEFAULT;for(a=0;a<b.length;a++){b[a].style.width=grid_size*map_size+
2+"px";b[a].style.height=grid_size*map_size+2+"px";for(var e=0;e<map_size;e++)for(var c=0;c<map_size;c++){var f=document.createElement("div");f.style.height=grid_size+"px";f.style.width=grid_size+"px";f.setAttribute("x",e);f.setAttribute("y",c);f.setAttribute("class","MonitorGrid");var g=e*grid_size,h=c*grid_size;f.style.top=g+"px";f.style.left=h+"px";var m=document.createElement("canvas");m.style.height=grid_size+"px";m.style.width=grid_size+"px";m.setAttribute("c-x",e);m.setAttribute("c-y",c);m.setAttribute("class",
"GridCanvas");m.style.top=g+"px";m.style.left=h+"px";f.appendChild(m);b[a].appendChild(f)}}document.getElementById("objective").innerHTML=string.game_objective_label;a=document.getElementById("objectiveList");document.getElementById("gameModeLabel").innerHTML=string.game_mode_label;document.getElementById("gameMode").innerHTML=string.game_mode[game_mode];switch(game_mode){case GAME_MODE_SKIRMISH:case GAME_MODE_INTERCEPT:case GAME_MODE_BREAKTHROUGH:b=document.createElement("li");b.innerHTML=string.game_objective_loading;
a.appendChild(b);max_ship_count=MAX_SHIP_COUNT_STANDARD;max_cv_count=MAX_CV_COUNT_STANDARD;max_bb_count=MAX_BB_COUNT_STANDARD;max_ca_count=MAX_CA_COUNT_STANDARD;max_dd_count=MAX_DD_COUNT_STANDARD;break;case GAME_MODE_CLASSIC:b=document.createElement("li");b.innerHTML=string.game_objective_standard;a.appendChild(b);max_ship_count=MAX_SHIP_COUNT_CLASSIC;max_cv_count=MAX_CV_COUNT_CLASSIC;max_bb_count=MAX_BB_COUNT_CLASSIC;max_ca_count=MAX_CA_COUNT_CLASSIC;max_dd_count=MAX_DD_COUNT_CLASSIC;break;case GAME_MODE_CONVOY:b=
document.createElement("li"),b.innerHTML=string.game_objective_loading,a.appendChild(b),max_ship_count=MAX_SHIP_COUNT_STANDARD,max_cv_count=MAX_CV_COUNT_STANDARD,max_bb_count=MAX_BB_COUNT_STANDARD,max_ca_count=MAX_CA_COUNT_STANDARD,max_dd_count=MAX_DD_COUNT_STANDARD,max_ap_count=AP_COUNT_CONVOY}document.getElementById("dataPanelLeft").style.height=grid_size*map_size+2+"px";document.getElementById("dataPanelRight").style.height=grid_size*map_size+2+"px";a=document.getElementById("rbutton");a.innerHTML=
string.rotate;a.style.display="none";a=document.createElement("p");a.innerHTML=string.ship_placement_remaining;a.setAttribute("id","counterLabelLeft");counter_label_left=a;document.getElementById("dataPanelContentLeft").appendChild(a);a=document.createElement("p");a.innerHTML=max_ship_count;a.setAttribute("class","Counter");a.setAttribute("id","counterLeft");counter_text_left=a;document.getElementById("dataPanelContentLeft").appendChild(a);player_1_ship_set=a=RNG(0,3);switch(game_mode){case GAME_MODE_SKIRMISH:case GAME_MODE_INTERCEPT:case GAME_MODE_BREAKTHROUGH:case GAME_MODE_CLASSIC:for(a=
0;a<=SHIP_CLASS_DD;a++){b=document.createElement("p");b.setAttribute("class","ShipClassLabel");b.innerHTML=string.ship_classes[a];document.getElementById("dataPanelContentLeft").appendChild(b);b=document.createElement("img");switch(a){case SHIP_CLASS_BB:case SHIP_CLASS_CV:var l="ShipIcons";break;case SHIP_CLASS_CA:l="ShipIcons ShipIconsCA";break;case SHIP_CLASS_DD:l="ShipIcons ShipIconsDD"}b.setAttribute("class",l);b.setAttribute("id",a);b.setAttribute("src",img_url.ship_icons[player_1_ship_set][a]);
document.getElementById("dataPanelContentLeft").appendChild(b)}break;case GAME_MODE_CONVOY:for(a=0;a<=SHIP_CLASS_AP;a++){b=document.createElement("p");b.setAttribute("class","ShipClassLabel");b.innerHTML=string.ship_classes[a];document.getElementById("dataPanelContentLeft").appendChild(b);b=document.createElement("img");switch(a){case SHIP_CLASS_BB:case SHIP_CLASS_CV:l="ShipIcons";break;case SHIP_CLASS_CA:l="ShipIcons ShipIconsCA";break;case SHIP_CLASS_DD:l="ShipIcons ShipIconsDD";break;case SHIP_CLASS_AP:l=
"ShipIcons ShipIconsCA"}b.setAttribute("class",l);b.setAttribute("id",a);b.setAttribute("src",img_url.ship_icons[player_1_ship_set][a]);document.getElementById("dataPanelContentLeft").appendChild(b)}}document.getElementById("apLeft").innerHTML=string.action_prompt_enemy;a=document.createElement("p");a.innerHTML=string.ship_placement_remaining;counter_label_right=a;document.getElementById("dataPanelContentRight").appendChild(a);a=document.createElement("p");a.innerHTML=max_ship_count;a.setAttribute("class",
"Counter");a.setAttribute("id","counterRight");counter_text_right=a;for(document.getElementById("dataPanelContentRight").appendChild(a);player_2_ship_set==player_1_ship_set;)player_2_ship_set=a=RNG(0,2);for(a=0;a<=SHIP_CLASS_DD;a++){b=document.createElement("p");b.setAttribute("class","ShipClassLabel");b.innerHTML=string.ship_classes[a];document.getElementById("dataPanelContentRight").appendChild(b);b=document.createElement("img");switch(a){case SHIP_CLASS_BB:case SHIP_CLASS_CV:l="ShipIconsEnemy ShipIcons";
break;case SHIP_CLASS_CA:l="ShipIconsEnemy ShipIcons ShipIconsCA";break;case SHIP_CLASS_DD:l="ShipIconsEnemy ShipIcons ShipIconsDD"}b.setAttribute("class",l);b.setAttribute("src",img_url.ship_icons[player_2_ship_set][a]);document.getElementById("dataPanelContentRight").appendChild(b)}document.getElementById("apRight").innerHTML=string.action_prompt_player;l=document.getElementById("mainButton");l.innerHTML=string.assemble_fleet;l.addEventListener("click",startShipPlacement,!1);document.getElementById("content").style.visibility=
"visible";document.getElementById("settingBox").style.display="none"}
function startShipPlacement(){document.getElementById("dataPanelContentRight").style.display="none";var a=document.createElement("p");a.innerHTML=string.pending;a.setAttribute("class","DataPanelOverlay");a.setAttribute("id","pending");document.getElementById("dataPanelRight").appendChild(a);for(var a=document.getElementById("dataPanelContentLeft").querySelectorAll(".ShipIcons"),b=0;b<a.length;b++){var e=a[b].getAttribute("class"),e=e+" ShipIconsSelectable";a[b].setAttribute("class",e)}a=document.querySelectorAll(".ShipIconsSelectable");
for(b=0;b<a.length;b++)a[b].addEventListener("click",onShipIconSelected,!1);document.getElementById("rbutton").addEventListener("click",function(){ship_course_placing=ship_course_placing==SHIP_COURSE_VERTICAL?SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL},!1);a=document.getElementById("mainButton");a.innerHTML=string.start_battle;a.removeEventListener("click",startShipPlacement,!1);a.addEventListener("click",startGame,!1)}
function onShipIconSelected(a){ship_class_placing=parseInt(a.target.id);a=document.getElementById("monitorLeft").getElementsByClassName("MonitorGrid");for(var b=0;b<a.length;b++)a[b].addEventListener("click",placeShip,!1),a[b].addEventListener("mouseover",projectShip,!1),a[b].addEventListener("mouseout",unProjectShip,!1),a[b].addEventListener("contextmenu",changeShipCourse,!1);window.oncontextmenu=function(){return!1};document.getElementById("rbutton").style.display="inline"}
function shipPlaceable(a,b){switch(ship_class_placing){case SHIP_CLASS_BB:case SHIP_CLASS_CV:ship_size_placing=4;break;case SHIP_CLASS_CA:case SHIP_CLASS_AP:ship_size_placing=3;break;case SHIP_CLASS_DD:ship_size_placing=2}if(ship_course_placing==SHIP_COURSE_VERTICAL){if(a+ship_size_placing<=map_size&&b<=map_size){for(var e=0;e<ship_size_placing;e++)if(document.querySelector("[x='"+(a+e)+"'][y='"+b+"']").hasAttribute("placed"))return!1;return!0}return!1}if(ship_course_placing==SHIP_COURSE_HORIZONTAL){if(b+
ship_size_placing<=map_size&&a<=map_size){for(e=0;e<ship_size_placing;e++)if(document.querySelector("[y='"+(b+e)+"'][x='"+a+"']").hasAttribute("placed"))return!1;return!0}return!1}}
function projectShip(a){var b=a.target;a=parseInt(b.getAttribute("x"));var e=parseInt(b.getAttribute("y"));if(shipPlaceable(a,e))if(ship_course_placing==SHIP_COURSE_VERTICAL)for(var c=0;c<ship_size_placing;c++)b=document.querySelector("[x='"+(a+c)+"'][y='"+e+"']"),b.style.backgroundImage="url('"+img_url.ship_tiles[ship_class_placing][0][c]+"')";else if(ship_course_placing==SHIP_COURSE_HORIZONTAL)for(c=0;c<ship_size_placing;c++)b=document.querySelector("[y='"+(e+c)+"'][x='"+a+"']"),b.style.backgroundImage=
"url('"+img_url.ship_tiles[ship_class_placing][0][c]+"')",b.classList.add("ShipsTileHorizontal")}
function unProjectShip(a){var b=a.target;a=parseInt(b.getAttribute("x"));var e=parseInt(b.getAttribute("y"));if(shipPlaceable(a,e))if(ship_course_placing==SHIP_COURSE_VERTICAL)for(var c=0;c<ship_size_placing;c++)b=document.querySelector("[x='"+(a+c)+"'][y='"+e+"']"),b.style.backgroundImage="";else if(ship_course_placing==SHIP_COURSE_HORIZONTAL)for(c=0;c<ship_size_placing;c++)b=document.querySelector("[y='"+(e+c)+"'][x='"+a+"']"),b.style.backgroundImage="",b.classList.remove("ShipsTileHorizontal")}
function changeShipCourse(a){unProjectShip(a);ship_course_placing=ship_course_placing==SHIP_COURSE_VERTICAL?SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL;projectShip(a)}
function placeShip(a){var b;a=a.target;var e=parseInt(a.getAttribute("x")),c=parseInt(a.getAttribute("y"));if(shipPlaceable(e,c)){if(ship_course_placing==SHIP_COURSE_VERTICAL)for(b=0;b<ship_size_placing;b++){var f=document.querySelector("[x='"+(e+b)+"'][y='"+c+"']");f.style.backgroundImage="url('"+img_url.ship_tiles[ship_class_placing][0][b]+"')";a=f.getAttribute("class");a+=" ShipsTile";f.setAttribute("class",a);f.setAttribute("placed","true");f.setAttribute("ship-class",ship_class_placing);f.setAttribute("ship-bearing",
ship_course_placing);f.setAttribute("sector",b);f.setAttribute("head-x",e);f.setAttribute("head-y",c);f.style.backgroundColor="";f.removeEventListener("click",placeShip,!1);f.removeEventListener("mouseover",projectShip,!1);f.removeEventListener("mouseout",unProjectShip,!1)}else if(ship_course_placing==SHIP_COURSE_HORIZONTAL)for(b=0;b<ship_size_placing;b++)f=document.querySelector("[y='"+(c+b)+"'][x='"+e+"']"),f.style.backgroundImage="url('"+img_url.ship_tiles[ship_class_placing][0][b]+"')",a=f.getAttribute("class"),
a+=" ShipsTileHorizontal",f.setAttribute("class",a),f.removeEventListener("click",placeShip,!1),f.setAttribute("placed","true"),f.setAttribute("ship-class",ship_class_placing),f.setAttribute("ship-bearing",ship_course_placing),f.setAttribute("sector",b),f.setAttribute("head-x",e),f.setAttribute("head-y",c),f.style.backgroundColor="",f.removeEventListener("mouseover",projectShip,!1),f.removeEventListener("mouseout",unProjectShip,!1);player_1_fleet_course+=ship_course_placing;document.getElementById("counterLeft").innerHTML=
parseInt(counter_text_left.innerHTML)-1;switch(ship_class_placing){case SHIP_CLASS_BB:player_1_ships_count[SHIP_CLASS_BB]+=1;if(player_1_ships_count[SHIP_CLASS_BB]>=max_bb_count){b=document.querySelectorAll(".ShipIcons");a=b[ship_class_placing].getAttribute("class");a=a.replace(" ShipIconsSelectable"," ShipIconsUnSelectable");b[ship_class_placing].setAttribute("class",a);b[ship_class_placing].removeEventListener("click",onShipIconSelected,!1);f=document.getElementById("monitorLeft").getElementsByClassName("MonitorGrid");
for(b=0;b<f.length;b++)f[b].removeEventListener("click",placeShip,!1),f[b].removeEventListener("mouseover",projectShip,!1),f[b].removeEventListener("mouseout",unProjectShip,!1),f[b].removeEventListener("contextmenu",changeShipCourse,!1);document.getElementById("rbutton").style.display="none"}break;case SHIP_CLASS_CV:player_1_ships_count[SHIP_CLASS_CV]+=1;if(player_1_ships_count[SHIP_CLASS_CV]>=max_cv_count){b=document.querySelectorAll(".ShipIcons");a=b[ship_class_placing].getAttribute("class");a=
a.replace(" ShipIconsSelectable"," ShipIconsUnSelectable");b[ship_class_placing].setAttribute("class",a);b[ship_class_placing].removeEventListener("click",onShipIconSelected,!1);f=document.getElementById("monitorLeft").getElementsByClassName("MonitorGrid");for(b=0;b<f.length;b++)f[b].removeEventListener("click",placeShip,!1),f[b].removeEventListener("mouseover",projectShip,!1),f[b].removeEventListener("mouseout",unProjectShip,!1),f[b].removeEventListener("contextmenu",changeShipCourse,!1);document.getElementById("rbutton").style.display=
"none"}break;case SHIP_CLASS_CA:player_1_ships_count[SHIP_CLASS_CA]+=1;if(player_1_ships_count[SHIP_CLASS_CA]>=max_ca_count){b=document.querySelectorAll(".ShipIcons");a=b[ship_class_placing].getAttribute("class");a=a.replace(" ShipIconsSelectable"," ShipIconsUnSelectable");b[ship_class_placing].setAttribute("class",a);b[ship_class_placing].removeEventListener("click",onShipIconSelected,!1);f=document.getElementById("monitorLeft").getElementsByClassName("MonitorGrid");for(b=0;b<f.length;b++)f[b].removeEventListener("click",
placeShip,!1),f[b].removeEventListener("mouseover",projectShip,!1),f[b].removeEventListener("mouseout",unProjectShip,!1),f[b].removeEventListener("contextmenu",changeShipCourse,!1);document.getElementById("rbutton").style.display="none"}break;case SHIP_CLASS_DD:player_1_ships_count[SHIP_CLASS_DD]+=1;if(player_1_ships_count[SHIP_CLASS_DD]>=max_dd_count){b=document.querySelectorAll(".ShipIcons");a=b[ship_class_placing].getAttribute("class");a=a.replace(" ShipIconsSelectable"," ShipIconsUnSelectable");
b[ship_class_placing].setAttribute("class",a);b[ship_class_placing].removeEventListener("click",onShipIconSelected,!1);f=document.getElementById("monitorLeft").getElementsByClassName("MonitorGrid");for(b=0;b<f.length;b++)f[b].removeEventListener("click",placeShip,!1),f[b].removeEventListener("mouseover",projectShip,!1),f[b].removeEventListener("mouseout",unProjectShip,!1),f[b].removeEventListener("contextmenu",changeShipCourse,!1);document.getElementById("rbutton").style.display="none"}break;case SHIP_CLASS_AP:if(player_1_ships_count[SHIP_CLASS_AP]+=
1,player_1_ships_count[SHIP_CLASS_AP]>=max_ap_count){b=document.querySelectorAll(".ShipIcons");a=b[ship_class_placing].getAttribute("class");a=a.replace(" ShipIconsSelectable"," ShipIconsUnSelectable");b[ship_class_placing].setAttribute("class",a);b[ship_class_placing].removeEventListener("click",onShipIconSelected,!1);f=document.getElementById("monitorLeft").getElementsByClassName("MonitorGrid");for(b=0;b<f.length;b++)f[b].removeEventListener("click",placeShip,!1),f[b].removeEventListener("mouseover",
projectShip,!1),f[b].removeEventListener("mouseout",unProjectShip,!1),f[b].removeEventListener("contextmenu",changeShipCourse,!1);document.getElementById("rbutton").style.display="none"}}getPlayerShipCount(PLAYER_1)>=max_ship_count&&stopPlayerShipPlacement();if(game_mode==GAME_MODE_CONVOY&&max_ship_count-getPlayerShipCount(PLAYER_1)<=max_ap_count-player_1_ships_count[SHIP_CLASS_AP]&&getPlayerShipCount(PLAYER_1)<max_ship_count&&ship_class_placing!=SHIP_CLASS_AP)for(a=document.querySelectorAll(".ShipIcons"),
e=0;e<a.length;e++)if(e!=SHIP_CLASS_AP){f=a[e].getAttribute("class");f=f.replace(" ShipIconsSelectable"," ShipIconsUnSelectable");a[e].setAttribute("class",f);a[e].removeEventListener("click",onShipIconSelected,!1);f=document.getElementById("monitorLeft").getElementsByClassName("MonitorGrid");for(c=0;c<f.length;c++)f[c].removeEventListener("click",placeShip,!1),f[c].removeEventListener("mouseover",projectShip,!1),f[c].removeEventListener("mouseout",unProjectShip,!1),f[b].removeEventListener("contextmenu",
changeShipCourse,!1);document.getElementById("rbutton").style.display="none"}}}
function stopPlayerShipPlacement(){var a=document.querySelectorAll(".ShipIcons");window.oncontextmenu=function(){return!0};for(var b=0;b<a.length;b++){a[b].removeEventListener("click",onShipIconSelected,!1);var e=a[b].getAttribute("class"),e=e.replace(" ShipIconsSelectable",""),e=e.replace(" ShipIconsUnSelectable","");a[b].setAttribute("class",e)}a=document.getElementById("monitorLeft").getElementsByClassName("MonitorGrid");for(b=0;b<a.length;b++)a[b].removeEventListener("click",placeShip,!1),a[b].removeEventListener("mouseover",
projectShip,!1),a[b].removeEventListener("mouseout",unProjectShip,!1);null!=document.getElementById("rbutton")&&(b=document.getElementById("rbutton"),b.parentNode.removeChild(b));getPlayerShipCount(PLAYER_2)<max_ship_count&&shipPlacementMain()}function getPlayerShipCount(a){return a==PLAYER_1?player_1_ships_count.reduce(function(a,e){return a+e},0):player_2_ships_count.reduce(function(a,e){return a+e},0)}
function startGame(){if(0>=getPlayerShipCount(PLAYER_1))alert(string.no_ship_prompt);else if(game_mode==GAME_MODE_CONVOY&&player_1_ships_count[SHIP_CLASS_AP]<max_ap_count)alert(string.no_ap_prompt);else{stopPlayerShipPlacement();var a=document.getElementById("mainButton");a.innerHTML=string.surrender;a.removeEventListener("click",startGame,!1);a.addEventListener("click",surrender,!1);for(var a=document.getElementById("dataPanelContentLeft").querySelectorAll(".ShipClassLabel"),b=0;b<a.length;b++)a[b].innerHTML=
a[b].innerHTML+" : "+player_1_ships_count[b];document.getElementById("counterLeft").innerHTML=getPlayerShipCount(PLAYER_1);document.getElementById("dataPanelContentRight").style.display="";a=document.getElementById("pending");a.parentNode.removeChild(a);a=document.getElementById("dataPanelContentRight").querySelectorAll(".ShipClassLabel");if(FOG_OF_WAR)for(b=0;b<a.length;b++)a[b].innerHTML+=" : ???";else for(b=0;b<a.length;b++)a[b].innerHTML=a[b].innerHTML+" : "+player_2_ships_count[b];document.getElementById("counterRight").innerHTML=
getPlayerShipCount(PLAYER_2);switch(game_mode){case GAME_MODE_SKIRMISH:player_1_fleet_speed=player_1_ships_count[SHIP_CLASS_BB]>=Math.round(getPlayerShipCount(PLAYER_1)/2)?FLEET_SPEED_SLOW:FLEET_SPEED_FAST;player_2_fleet_speed=player_2_ships_count[SHIP_CLASS_BB]>=Math.round(getPlayerShipCount(PLAYER_2)/2)?FLEET_SPEED_SLOW:FLEET_SPEED_FAST;player_1_fleet_course=player_1_fleet_course>=Math.round(getPlayerShipCount(PLAYER_1)/2)?SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL;player_2_fleet_course=player_2_fleet_course>=
Math.round(getPlayerShipCount(PLAYER_2)/2)?SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL;a=document.getElementById("objectiveList");b=document.createElement("li");b.innerHTML=string.game_objective_standard;a.innerHTML="";a.appendChild(b);aerialCombat();break;case GAME_MODE_INTERCEPT:player_1_fleet_speed=player_1_ships_count[SHIP_CLASS_BB]>=Math.round(getPlayerShipCount(PLAYER_1)/2)?FLEET_SPEED_SLOW:FLEET_SPEED_FAST;player_2_fleet_speed=player_2_ships_count[SHIP_CLASS_BB]>=Math.round(getPlayerShipCount(PLAYER_2)/
2)?FLEET_SPEED_SLOW:FLEET_SPEED_FAST;player_1_fleet_course=player_1_fleet_course>=Math.round(getPlayerShipCount(PLAYER_1)/2)?SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL;player_2_fleet_course=player_2_fleet_course>=Math.round(getPlayerShipCount(PLAYER_2)/2)?SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL;SPECIFIC_CLASS_INTERCEPT_BREAKTHROUGH&&(0<player_2_ships_count[SHIP_CLASS_CV]&&0<player_2_ships_count[SHIP_CLASS_BB]?ship_class_target=RNG(SHIP_CLASS_BB,SHIP_CLASS_CV):0<player_2_ships_count[SHIP_CLASS_BB]?
ship_class_target=SHIP_CLASS_BB:0<player_2_ships_count[SHIP_CLASS_CV]?ship_class_target=SHIP_CLASS_CV:SPECIFIC_CLASS_INTERCEPT_BREAKTHROUGH=!1);a=document.getElementById("objectiveList");b=document.createElement("li");b.innerHTML=SPECIFIC_CLASS_INTERCEPT_BREAKTHROUGH?ship_class_target==SHIP_CLASS_BB?string.game_objective_intercept_bb:string.game_objective_intercept_cv:string.game_objective_standard;a.innerHTML="";a.appendChild(b);document.getElementById("TurnCounterField").style.visibility="visible";
document.getElementById("TurnCounterLabel").innerHTML=string.turn_counter_label;document.getElementById("TurnCounter").innerHTML=max_turn_intercept_breakthrough-total_turn_counter;aerialCombat();break;case GAME_MODE_BREAKTHROUGH:player_1_fleet_speed=player_1_ships_count[SHIP_CLASS_BB]>=Math.round(getPlayerShipCount(PLAYER_1)/2)?FLEET_SPEED_SLOW:FLEET_SPEED_FAST;player_2_fleet_speed=player_2_ships_count[SHIP_CLASS_BB]>=Math.round(getPlayerShipCount(PLAYER_2)/2)?FLEET_SPEED_SLOW:FLEET_SPEED_FAST;player_1_fleet_course=
player_1_fleet_course>=Math.round(getPlayerShipCount(PLAYER_1)/2)?SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL;player_2_fleet_course=player_2_fleet_course>=Math.round(getPlayerShipCount(PLAYER_2)/2)?SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL;SPECIFIC_CLASS_INTERCEPT_BREAKTHROUGH&&(0<player_1_ships_count[SHIP_CLASS_CV]&&0<player_1_ships_count[SHIP_CLASS_BB]?ship_class_target=RNG(SHIP_CLASS_BB,SHIP_CLASS_CV):0<player_1_ships_count[SHIP_CLASS_BB]?ship_class_target=SHIP_CLASS_BB:0<player_1_ships_count[SHIP_CLASS_CV]?
ship_class_target=SHIP_CLASS_CV:SPECIFIC_CLASS_INTERCEPT_BREAKTHROUGH=!1);a=document.getElementById("objectiveList");b=document.createElement("li");b.innerHTML=SPECIFIC_CLASS_INTERCEPT_BREAKTHROUGH?ship_class_target==SHIP_CLASS_BB?string.game_objective_breakthrough_bb:string.game_objective_breakthrough_cv:string.game_objective_breakthrough;a.innerHTML="";a.appendChild(b);document.getElementById("TurnCounterField").style.visibility="visible";document.getElementById("TurnCounterLabel").innerHTML=string.turn_counter_label;
document.getElementById("TurnCounter").innerHTML=max_turn_intercept_breakthrough-total_turn_counter;aerialCombat();break;case GAME_MODE_CONVOY:player_1_fleet_speed=player_1_ships_count[SHIP_CLASS_BB]>=Math.round(getPlayerShipCount(PLAYER_1)/2)?FLEET_SPEED_SLOW:FLEET_SPEED_FAST;player_2_fleet_speed=player_2_ships_count[SHIP_CLASS_BB]>=Math.round(getPlayerShipCount(PLAYER_2)/2)?FLEET_SPEED_SLOW:FLEET_SPEED_FAST;player_1_fleet_course=player_1_fleet_course>=Math.round(getPlayerShipCount(PLAYER_1)/2)?
SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL;player_2_fleet_course=player_2_fleet_course>=Math.round(getPlayerShipCount(PLAYER_2)/2)?SHIP_COURSE_HORIZONTAL:SHIP_COURSE_VERTICAL;a=document.getElementById("objectiveList");b=document.createElement("li");b.innerHTML=string.game_objective_convoy;a.innerHTML="";a.appendChild(b);document.getElementById("TurnCounterField").style.visibility="visible";document.getElementById("TurnCounterLabel").innerHTML=string.turn_counter_label;document.getElementById("TurnCounter").innerHTML=
max_turn_intercept_breakthrough-total_turn_counter;aerialCombat();break;case GAME_MODE_CLASSIC:startFleetCombat()}}}
function aerialCombat(){game_phase=GAME_PAHSE_AERIAL_COMBAT;ship_class_acting=SHIP_CLASS_CV;document.getElementById("stage").innerHTML=string.game_stage_aerial;RNG(PLAYER_1,PLAYER_2)==PLAYER_1?(acting_player=PLAYER_1,promptAction(),player_1_attack_count=2*player_1_ships_count[SHIP_CLASS_CV],0<player_1_attack_count?beginTargeting():nextPlayer()):(acting_player=PLAYER_2,promptAction(),player_2_attack_count=2*player_2_ships_count[SHIP_CLASS_CV],0<player_2_attack_count?attackMain():nextPlayer())}
function startFleetCombat(){game_phase=GAME_PHASE_COMBAT;document.getElementById("stage").innerHTML=string.game_stage_artillery;switch(game_mode){case GAME_MODE_SKIRMISH:case GAME_MODE_INTERCEPT:case GAME_MODE_BREAKTHROUGH:case GAME_MODE_CONVOY:player_1_fleet_course==player_2_fleet_course?player_2_engagement_form=player_1_engagement_form=RNG(ENGAGEMENT_FORM_PARALLEL,ENGAGEMENT_FORM_HEADON):player_1_fleet_speed!=player_2_fleet_speed?player_1_fleet_speed==FLEET_SPEED_SLOW?(player_1_engagement_form=
ENGAGEMENT_FORM_T_DIS,player_2_engagement_form=ENGAGEMENT_FORM_T_ADV):player_2_fleet_speed==FLEET_SPEED_SLOW&&(player_1_engagement_form=ENGAGEMENT_FORM_T_ADV,player_2_engagement_form=ENGAGEMENT_FORM_T_DIS):(player_1_engagement_form=RNG(ENGAGEMENT_FORM_T_ADV,ENGAGEMENT_FORM_T_DIS),player_2_engagement_form=player_1_engagement_form==ENGAGEMENT_FORM_T_DIS?ENGAGEMENT_FORM_T_ADV:ENGAGEMENT_FORM_T_DIS)}FOG_OF_WAR||(document.getElementById("FoELabel").innerHTML=string.form_of_engagement_label,document.getElementById("FoE").innerHTML=
string.form_of_engagement[player_1_engagement_form]);player_2_acted=player_1_acted=!1;if(RNG(PLAYER_1,PLAYER_2)==PLAYER_1){acting_player=PLAYER_1;switch(game_mode){case GAME_MODE_SKIRMISH:case GAME_MODE_INTERCEPT:player_1_turn_counter<=player_1_ships_count[SHIP_CLASS_BB]&&(ship_class_acting=SHIP_CLASS_BB,player_1_attack_count=BB_ATTACK_COUNT[player_1_engagement_form]);break;case GAME_MODE_CLASSIC:0<getPlayerShipCount(PLAYER_1)&&(player_1_attack_count=1)}0<player_1_attack_count?(player_1_turn_counter+=
1,beginTargeting()):nextPlayer()}else{acting_player=PLAYER_2;switch(game_mode){case GAME_MODE_SKIRMISH:player_2_turn_counter<=player_2_ships_count[SHIP_CLASS_BB]&&(ship_class_acting=SHIP_CLASS_BB,player_2_attack_count=BB_ATTACK_COUNT[player_2_engagement_form]);break;case GAME_MODE_CLASSIC:0<getPlayerShipCount(PLAYER_2)&&(player_2_attack_count=1)}0<player_2_attack_count?(player_2_turn_counter+=1,promptAction(),attackMain()):nextPlayer()}}
function beginTargeting(){promptAction();document.getElementById("counterLeft").innerHTML=player_1_attack_count;document.getElementById("counterLabelLeft").innerHTML=string.attack_remaining;for(var a=document.getElementById("monitorRight").getElementsByClassName("MonitorGrid"),b=0;b<a.length;b++)a[b].hasAttribute("sunk")||a[b].addEventListener("click",fire,!1),a[b].hasAttribute("sunk")||a[b].hasAttribute("hit_count")||(a[b].addEventListener("mouseover",lockOnSector,!1),a[b].addEventListener("mouseout",
unLockOnSector,!1))}function fire(a){var b=a.target;a=parseInt(b.getAttribute("x"));b=parseInt(b.getAttribute("y"));acting_player==PLAYER_1?(--player_1_attack_count,document.getElementById("counterLeft").innerHTML=player_1_attack_count):acting_player==PLAYER_2&&--player_2_attack_count;stopTargeting();ship_class_acting==SHIP_CLASS_CV?airStrike(a,b):artilleryStrike(a,b)}
function airStrike(a,b){SOUND_ENABLED?(plane_attack_sound.play(),setTimeout(function(){onAttackLanded(a,b)},1E3*plane_attack_sound.duration+800)):onAttackLanded(a,b)}function artilleryStrike(a,b){SOUND_ENABLED&&acting_player==PLAYER_1?(gun_fire_sound.play(),setTimeout(function(){onAttackLanded(a,b)},1E3*gun_fire_sound.duration+800)):onAttackLanded(a,b)}
function onAttackLanded(a,b){if(acting_player==PLAYER_1){var e=document.getElementById("monitorRight").querySelector("[y='"+b+"'][x='"+a+"']");if(e.hasAttribute("hit_count")){var c=parseInt(e.getAttribute("hit_count"));e.setAttribute("hit_count",c+1)}else e.setAttribute("hit_count","1");e.style.backgroundColor="navy";e.style.backgroundImage="";if(e.hasAttribute("placed")){e.style.backgroundColor="";e.style.backgroundImage="";if(e.hasAttribute("effectId")){var f=parseInt(e.getAttribute("effectId"));
clearInterval(f)}var g=e.firstElementChild;var h=[];for(c=0;8>c;c++)h.push(new explosionParticle);var m=setInterval(function(){showExplosion(g,h,!0)},40);setTimeout(function(){var a;clearInterval(m);if(!e.hasAttribute("sunk")){if(1>=parseInt(e.getAttribute("hit_count"))){var b=e.firstElementChild;var c=[];for(a=0;8>a;a++)c.push(new smokeParticle);a=e.classList.contains("ShipsTileHorizontal")?setInterval(function(){showSmoke(b,c,!0)},40):setInterval(function(){showSmoke(b,c,!1)},40)}else{a=parseInt(e.getAttribute("effectId"));
clearInterval(a);b=e.firstElementChild;var f=[],g=[];for(a=0;10>a;a++)f.push(new fireParticle);for(a=0;5>a;a++)g.push(new smokeParticle);a=e.classList.contains("ShipsTileHorizontal")?setInterval(function(){showFire(b,f,g,!0)},40):setInterval(function(){showFire(b,f,g,!1)},40)}e.setAttribute("effectId",a)}},1200);if(shipDestroyed("monitorRight",a,b)){var l=parseInt(e.getAttribute("head-x"));b=parseInt(e.getAttribute("head-y"));a=parseInt(e.getAttribute("ship-class"));c=parseInt(e.getAttribute("ship-bearing"));
switch(a){case SHIP_CLASS_BB:var n=4;--player_2_ships_count[SHIP_CLASS_BB];break;case SHIP_CLASS_CV:n=4;--player_2_ships_count[SHIP_CLASS_CV];break;case SHIP_CLASS_CA:n=3;--player_2_ships_count[SHIP_CLASS_CA];break;case SHIP_CLASS_DD:n=2,--player_2_ships_count[SHIP_CLASS_DD]}FOG_OF_WAR?document.getElementById("counterRight").innerHTML=getPlayerShipCount(PLAYER_2):refreshEnemyPanel();if(c==SHIP_COURSE_VERTICAL)for(c=0;c<n;c++){var k=document.getElementById("monitorRight").querySelector("[x='"+(l+c)+
"'][y='"+b+"']");FOG_OF_WAR?k.style.backgroundColor="#990000":k.style.backgroundImage="url('"+img_url.ship_tiles[a][2][c]+"')";k.setAttribute("sunk","true");f=parseInt(k.getAttribute("effectId"));clearInterval(f);f=k.firstElementChild;clearCanvas(f);k.removeEventListener("click",fire,!1)}else if(c==SHIP_COURSE_HORIZONTAL)for(c=0;c<n;c++)k=document.getElementById("monitorRight").querySelector("[y='"+(b+c)+"'][x='"+l+"']"),FOG_OF_WAR?k.style.backgroundColor="#990000":k.style.backgroundImage="url('"+
img_url.ship_tiles[a][2][c]+"')",k.setAttribute("sunk","true"),f=parseInt(k.getAttribute("effectId")),clearInterval(f),f=k.firstElementChild,clearCanvas(f),k.removeEventListener("click",fire,!1)}SOUND_ENABLED?(attack_hit_sound_distant.play(),setTimeout(function(){0<player_1_attack_count?beginTargeting():nextPlayer()},1E3*attack_hit_sound_distant.duration+800)):setTimeout(function(){0<player_1_attack_count?beginTargeting():nextPlayer()},1200)}else{g=e.firstElementChild;h=[];for(c=0;340>c;c++)h.push(new waterParticle);
var p=e.classList.contains("ShipsTileHorizontal")?setInterval(function(){showWaterSplash(g,h,!0)},60):setInterval(function(){showWaterSplash(g,h,!1)},60);SOUND_ENABLED?(attack_miss_sound.play(),setTimeout(function(){clearInterval(p);0<player_1_attack_count?beginTargeting():nextPlayer()},1E3*attack_miss_sound.duration+800)):setTimeout(function(){clearInterval(p);0<player_1_attack_count?beginTargeting():nextPlayer()},3E3)}}else if(acting_player==PLAYER_2)if(e=document.getElementById("monitorLeft").querySelector("[y='"+
b+"'][x='"+a+"']"),e.hasAttribute("hit_count")?(c=parseInt(e.getAttribute("hit_count")),e.setAttribute("hit_count",c+1)):e.setAttribute("hit_count","1"),e.style.backgroundColor="navy",e.hasAttribute("placed")){e.style.backgroundColor="";e.hasAttribute("effectId")&&(f=parseInt(e.getAttribute("effectId")),clearInterval(f));g=e.firstElementChild;h=[];for(c=0;8>c;c++)h.push(new explosionParticle);m=setInterval(function(){showExplosion(g,h,!0)},40);setTimeout(function(){var a;clearInterval(m);if(!e.hasAttribute("sunk")){if(1>=
parseInt(e.getAttribute("hit_count"))){var b=e.firstElementChild;var c=[];for(a=0;8>a;a++)c.push(new smokeParticle);a=e.classList.contains("ShipsTileHorizontal")?setInterval(function(){showSmoke(b,c,!0)},40):setInterval(function(){showSmoke(b,c,!1)},40)}else{a=parseInt(e.getAttribute("effectId"));clearInterval(a);b=e.firstElementChild;var f=[],g=[];for(a=0;10>a;a++)f.push(new fireParticle);for(a=0;5>a;a++)g.push(new smokeParticle);a=e.classList.contains("ShipsTileHorizontal")?setInterval(function(){showFire(b,
f,g,!0)},40):setInterval(function(){showFire(b,f,g,!1)},40)}e.setAttribute("effectId",a)}},1200);if(shipDestroyed("monitorLeft",a,b)){l=parseInt(e.getAttribute("head-x"));b=parseInt(e.getAttribute("head-y"));a=parseInt(e.getAttribute("ship-class"));c=parseInt(e.getAttribute("ship-bearing"));switch(a){case SHIP_CLASS_BB:n=4;--player_1_ships_count[SHIP_CLASS_BB];break;case SHIP_CLASS_CV:n=4;--player_1_ships_count[SHIP_CLASS_CV];break;case SHIP_CLASS_CA:n=3;--player_1_ships_count[SHIP_CLASS_CA];break;
case SHIP_CLASS_DD:n=2,--player_1_ships_count[SHIP_CLASS_DD]}refreshPlayerPanel();if(c==SHIP_COURSE_VERTICAL)for(c=0;c<n;c++)k=document.getElementById("monitorLeft").querySelector("[x='"+(l+c)+"'][y='"+b+"']"),k.style.backgroundImage="url('"+img_url.ship_tiles[a][2][c]+"')",f=parseInt(k.getAttribute("effectId")),clearInterval(f),f=k.firstElementChild,clearCanvas(f),k.setAttribute("sunk","true");else if(c==SHIP_COURSE_HORIZONTAL)for(c=0;c<n;c++)k=document.getElementById("monitorLeft").querySelector("[y='"+
(b+c)+"'][x='"+l+"']"),k.style.backgroundImage="url('"+img_url.ship_tiles[a][2][c]+"')",f=parseInt(k.getAttribute("effectId")),clearInterval(f),f=k.firstElementChild,clearCanvas(f),k.setAttribute("sunk","true")}onAttackResult(!0);SOUND_ENABLED?(attack_hit_sound.play(),setTimeout(function(){0<player_2_attack_count?attackMain():nextPlayer()},1E3*attack_hit_sound.duration+800)):setTimeout(function(){clearInterval(p);0<player_2_attack_count?attackMain():nextPlayer()},1200)}else{g=e.firstElementChild;
h=[];for(c=0;340>c;c++)h.push(new waterParticle);p=e.classList.contains("ShipsTileHorizontal")?setInterval(function(){showWaterSplash(g,h,!0)},60):setInterval(function(){showWaterSplash(g,h,!1)},60);onAttackResult(!1);SOUND_ENABLED?(attack_miss_sound.play(),setTimeout(function(){clearInterval(p);0<player_2_attack_count?attackMain():nextPlayer()},1E3*attack_miss_sound.duration+800)):setTimeout(function(){clearInterval(p);0<player_2_attack_count?attackMain():nextPlayer()},3E3)}}
function showSmoke(a,b,e){var c=a.getContext("2d");a.width=grid_size;a.height=grid_size;c.globalCompositeOperation="source-over";1==e&&(c.translate(a.width/2,a.height/2),c.rotate(Math.PI/2),c.translate(-a.width/2,-a.height/2));c.clearRect(0,0,grid_size,grid_size);for(a=0;a<b.length;a++){e=b[a];c.beginPath();e.opacity=Math.round(e.remaining_life/e.life*100)/100;var f=c.createRadialGradient(e.location.x,e.location.y,0,e.location.x,e.location.y,e.radius);f.addColorStop(0,"rgba("+e.r+", "+e.g+", "+e.b+
", "+e.opacity+")");f.addColorStop(.5,"rgba("+e.r+", "+e.g+", "+e.b+", "+e.opacity+")");f.addColorStop(1,"rgba("+e.r+", "+e.g+", "+e.b+", 0)");c.fillStyle=f;c.arc(e.location.x,e.location.y,e.radius,2*Math.PI,!1);c.fill();e.remaining_life--;e.location.x+=e.speed.x;e.location.y+=e.speed.y;0>e.remaining_life&&(b[a]=new smokeParticle)}}
function showFire(a,b,e,c){var f=a.getContext("2d");a.width=grid_size;a.height=grid_size;f.globalCompositeOperation="source-over";1==c&&(f.translate(a.width/2,a.height/2),f.rotate(Math.PI/2),f.translate(-a.width/2,-a.height/2));f.clearRect(0,0,grid_size,grid_size);for(var g=0;g<b.length;g++)c=b[g],f.beginPath(),c.opacity=Math.round(c.remaining_life/c.life*100)/100,a=f.createRadialGradient(c.location.x,c.location.y,0,c.location.x,c.location.y,c.radius),a.addColorStop(0,"rgba("+c.colorStop1.r+", "+
c.colorStop1.g+", "+c.colorStop1.b+", "+c.opacity+")"),a.addColorStop(.4,"rgba("+c.colorStop2.r+", "+c.colorStop2.g+", "+c.colorStop2.b+", "+c.opacity+")"),a.addColorStop(.6,"rgba("+c.colorStop3.r+", "+c.colorStop3.g+", "+c.colorStop3.b+", "+c.opacity+")"),a.addColorStop(1,"rgba("+c.colorStop1.r+", "+c.colorStop1.g+", "+c.colorStop1.b+", 0)"),f.fillStyle=a,f.arc(c.location.x,c.location.y,c.radius,2*Math.PI,!1),f.fill(),c.remaining_life--,c.location.x+=c.speed.x,c.location.y+=c.speed.y,0>c.remaining_life&&
(b[g]=new fireParticle);for(g=0;g<e.length;g++)c=e[g],f.beginPath(),c.opacity=Math.round(c.remaining_life/c.life*100)/100,a=f.createRadialGradient(c.location.x,c.location.y,0,c.location.x,c.location.y,c.radius),a.addColorStop(0,"rgba("+c.r+", "+c.g+", "+c.b+", "+c.opacity+")"),a.addColorStop(.5,"rgba("+c.r+", "+c.g+", "+c.b+", "+c.opacity+")"),a.addColorStop(1,"rgba("+c.r+", "+c.g+", "+c.b+", 0)"),f.fillStyle=a,f.arc(c.location.x,c.location.y,c.radius,2*Math.PI,!1),f.fill(),c.remaining_life--,c.location.x+=
c.speed.x,c.location.y+=c.speed.y,0>c.remaining_life&&(e[g]=new smokeParticle)}
function showExplosion(a,b){var e=a.getContext("2d");a.width=grid_size;a.height=grid_size;e.globalCompositeOperation="lighter";e.clearRect(0,0,grid_size,grid_size);for(a=0;a<b.length;a++){var c=b[a];e.beginPath();c.opacity=Math.round(c.remaining_life/c.life*100)/100;var f=e.createRadialGradient(c.location.x,c.location.y,0,c.location.x,c.location.y,c.radius);f.addColorStop(0,"rgba("+c.colorStop1.r+", "+c.colorStop1.g+", "+c.colorStop1.b+", "+c.opacity+")");f.addColorStop(.4,"rgba("+c.colorStop2.r+
", "+c.colorStop2.g+", "+c.colorStop2.b+", "+c.opacity+")");f.addColorStop(.6,"rgba("+c.colorStop3.r+", "+c.colorStop3.g+", "+c.colorStop3.b+", "+c.opacity+")");f.addColorStop(.8,"rgba("+c.colorStop4.r+", "+c.colorStop4.g+", "+c.colorStop4.b+", "+c.opacity+")");f.addColorStop(1,"rgba("+c.colorStop4.r+", "+c.colorStop4.g+", "+c.colorStop4.b+", 0)");e.fillStyle=f;e.arc(c.location.x,c.location.y,c.radius,2*Math.PI,!1);e.fill();c.remaining_life--;c.location.x+=c.speed.x;c.location.y+=c.speed.y}}
function showWaterSplash(a,b,e){var c=a.getContext("2d");a.width=grid_size;a.height=grid_size;c.globalCompositeOperation="source-over";1==e&&(c.translate(a.width/2,a.height/2),c.rotate(Math.PI/2),c.translate(-a.width/2,-a.height/2));c.clearRect(0,0,grid_size,grid_size);for(a=0;a<b.length;a++)e=b[a],c.beginPath(),c.fillStyle="rgb("+e.color.r+", "+e.color.g+", "+e.color.b+")",c.arc(e.location.x,e.location.y,e.radius,2*Math.PI,!1),c.fill(),e.location.x+=e.speed.x,e.location.y+=e.speed.y,e.speed.y-=e.gravityPull}
function smokeParticle(){this.speed={x:-.5+1*Math.random(),y:-2+2*Math.random()};this.location={x:grid_size/2,y:grid_size/2};this.radius=9;this.remaining_life=this.life=18+5*Math.random();var a=Math.round(60+40*Math.random());this.b=this.g=this.r=a}
function fireParticle(){this.speed={x:-.7+1*Math.random(),y:-.5+.5*Math.random()};this.location={x:grid_size/2,y:grid_size/2};this.radius=8;this.remaining_life=this.life=8+3*Math.random();this.colorStop1={r:255,g:255,b:255};this.colorStop2={r:255,g:255,b:Math.round(200+30*Math.random())};this.colorStop3={r:255,g:235,b:Math.round(90+30*Math.random())}}
function explosionParticle(){this.speed={x:-.5+1*Math.random(),y:-.5+1*Math.random()};this.location={x:grid_size/2,y:grid_size/2};this.radius=8;this.remaining_life=this.life=15+5*Math.random();this.colorStop1={r:255,g:255,b:255};this.colorStop2={r:255,g:255,b:Math.round(200+30*Math.random())};this.colorStop3={r:255,g:235,b:Math.round(90+30*Math.random())};this.colorStop4={r:255,g:204,b:Math.round(0+10*Math.random())}}
function waterParticle(){this.speed={x:(-.25+.5*Math.random())/DEFAULT_GRID_SIZE*grid_size,y:(-2.5+3*Math.random())/DEFAULT_GRID_SIZE*grid_size};this.gravityPull=-.2;this.location={x:grid_size/2-1.5+3/DEFAULT_GRID_SIZE*Math.random()*grid_size,y:grid_size-1};this.radius=1;this.color={r:160,g:210,b:Math.round(200+30*Math.random())}}function clearCanvas(a){a.getContext("2d").clearRect(0,0,grid_size,grid_size)}
function shipDestroyed(a,b,e){var c=document.getElementById(a).querySelector("[y='"+e+"'][x='"+b+"']");b=parseInt(c.getAttribute("head-x"));e=parseInt(c.getAttribute("head-y"));var f=parseInt(c.getAttribute("ship-class"));var c=parseInt(c.getAttribute("ship-bearing"));switch(f){case SHIP_CLASS_BB:var g=4;var h=game_mode==GAME_MODE_CLASSIC?1:2;break;case SHIP_CLASS_CV:g=4;h=1;break;case SHIP_CLASS_CA:g=3;h=1;break;case SHIP_CLASS_DD:g=2,h=1}if(c==SHIP_COURSE_VERTICAL)for(c=0;c<g;c++)if(f=document.getElementById(a).querySelector("[x='"+
(b+c)+"'][y='"+e+"']"),f.hasAttribute("hit_count"))if(parseInt(f.getAttribute("hit_count"))>=h){if(c==g-1)return!0}else return!1;else return!1;else if(c==SHIP_COURSE_HORIZONTAL)for(c=0;c<g;c++)if(f=document.getElementById(a).querySelector("[y='"+(e+c)+"'][x='"+b+"']"),f.hasAttribute("hit_count"))if(parseInt(f.getAttribute("hit_count"))>=h){if(c==g-1)return!0}else return!1;else return!1}
function lockOnSector(a){a=a.target;var b=document.createElement("img");b.setAttribute("src",img_url.crosshair);b.setAttribute("class","Crosshair");a.appendChild(b)}function unLockOnSector(a){a=a.target;"Crosshair"==a.childNodes[a.childNodes.length-1].getAttribute("class")&&a.removeChild(a.childNodes[a.childNodes.length-1])}
function stopTargeting(){hideActionPrompt();document.getElementById("counterLeft").innerHTML=getPlayerShipCount(PLAYER_1);document.getElementById("counterLabelLeft").innerHTML=string.ship_placement_remaining;for(var a=document.getElementById("monitorRight").getElementsByClassName("MonitorGrid"),b=0;b<a.length;b++)a[b].removeEventListener("click",fire,!1),a[b].removeEventListener("mouseover",lockOnSector,!1)}
function promptAction(){acting_player==PLAYER_1?document.getElementById("apRight").style.visibility="visible":document.getElementById("apLeft").style.visibility="visible"}function hideActionPrompt(){acting_player==PLAYER_1?document.getElementById("apRight").style.visibility="hidden":document.getElementById("apLeft").style.visibility="hidden"}
function refreshPlayerPanel(){document.getElementById("counterLeft").innerHTML=getPlayerShipCount(PLAYER_1);for(var a=document.getElementById("dataPanelContentLeft").querySelectorAll(".ShipClassLabel"),b=0;b<a.length;b++)switch(b){case SHIP_CLASS_BB:a[b].innerHTML=string.ship_classes[b]+" : "+player_1_ships_count[SHIP_CLASS_BB];break;case SHIP_CLASS_CV:a[b].innerHTML=string.ship_classes[b]+" : "+player_1_ships_count[SHIP_CLASS_CV];break;case SHIP_CLASS_CA:a[b].innerHTML=string.ship_classes[b]+" : "+
player_1_ships_count[SHIP_CLASS_CA];break;case SHIP_CLASS_DD:a[b].innerHTML=string.ship_classes[b]+" : "+player_1_ships_count[SHIP_CLASS_DD]}}
function refreshEnemyPanel(){document.getElementById("counterRight").innerHTML=getPlayerShipCount(PLAYER_2);for(var a=document.getElementById("dataPanelContentRight").querySelectorAll(".ShipClassLabel"),b=0;b<a.length;b++)switch(b){case SHIP_CLASS_BB:a[b].innerHTML=string.ship_classes[b]+" : "+player_2_ships_count[SHIP_CLASS_BB];break;case SHIP_CLASS_CV:a[b].innerHTML=string.ship_classes[b]+" : "+player_2_ships_count[SHIP_CLASS_CV];break;case SHIP_CLASS_CA:a[b].innerHTML=string.ship_classes[b]+" : "+
player_2_ships_count[SHIP_CLASS_CA];break;case SHIP_CLASS_DD:a[b].innerHTML=string.ship_classes[b]+" : "+player_2_ships_count[SHIP_CLASS_DD]}}
function nextPlayer(){if(gameEnded()){refreshPlayerPanel();refreshEnemyPanel();hideActionPrompt();var a=document.getElementById("mainButton");a.innerHTML=string.new_game;a.removeEventListener("click",surrender,!1);a.addEventListener("click",newGame,!1)}else if(acting_player==PLAYER_1)switch(hideActionPrompt(),acting_player=PLAYER_2,promptAction(),game_mode){case GAME_MODE_SKIRMISH:case GAME_MODE_INTERCEPT:case GAME_MODE_CONVOY:case GAME_MODE_BREAKTHROUGH:game_phase==GAME_PAHSE_AERIAL_COMBAT?(player_1_acted=
!0,player_2_attack_count=2*player_2_ships_count[SHIP_CLASS_CV],0<player_2_attack_count&&!player_2_acted?attackMain():startFleetCombat()):game_phase==GAME_PHASE_COMBAT&&(player_2_first_act_complete?(player_2_turn_counter<=player_2_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_BB,player_2_attack_count=BB_ATTACK_COUNT[player_2_engagement_form]):player_2_turn_counter<=player_2_ships_count[SHIP_CLASS_CA]+player_2_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_CA,player_2_attack_count=
CA_ATTACK_COUNT[player_2_engagement_form]):player_2_turn_counter<=player_2_ships_count[SHIP_CLASS_DD]+player_2_ships_count[SHIP_CLASS_CA]+player_2_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_DD,player_2_attack_count=DD_ATTACK_COUNT[player_2_engagement_form]):player_2_turn_counter<=player_2_ships_count[SHIP_CLASS_CV]+player_2_ships_count[SHIP_CLASS_DD]+player_2_ships_count[SHIP_CLASS_CA]+player_2_ships_count[SHIP_CLASS_BB]&&(ship_class_acting=SHIP_CLASS_CV,player_2_attack_count=CV_ATTACK_COUNT[player_2_engagement_form]),
player_2_turn_counter+=1,player_2_turn_counter>getPlayerShipCount(PLAYER_2)-player_2_ships_count[SHIP_CLASS_AP]&&(player_2_acted=!0),player_2_acted&&player_1_acted&&(player_1_turn_counter=player_2_turn_counter=0,total_turn_counter+=1,game_mode!=GAME_MODE_INTERCEPT&&game_mode!=GAME_MODE_CONVOY&&game_mode!=GAME_MODE_BREAKTHROUGH||updateTurnCounter(),player_1_acted=player_2_acted=!1),0<player_2_attack_count?attackMain():nextPlayer()):(player_2_turn_counter>=getPlayerShipCount(PLAYER_2)&&(player_2_first_act_complete=
!0),player_2_turn_counter<player_2_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_BB,player_2_attack_count=BB_ATTACK_COUNT[player_2_engagement_form],0<player_2_attack_count&&(player_2_turn_counter+=1,attackMain())):player_1_turn_counter<player_1_ships_count[SHIP_CLASS_BB]?nextPlayer():player_2_turn_counter<player_2_ships_count[SHIP_CLASS_CA]+player_2_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_CA,player_2_attack_count=CA_ATTACK_COUNT[player_2_engagement_form],0<player_2_attack_count?
(player_2_turn_counter+=1,attackMain()):(player_2_turn_counter+=1,nextPlayer())):player_1_turn_counter<player_1_ships_count[SHIP_CLASS_CA]+player_1_ships_count[SHIP_CLASS_BB]?nextPlayer():player_2_turn_counter<player_2_ships_count[SHIP_CLASS_DD]+player_2_ships_count[SHIP_CLASS_CA]+player_2_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_DD,player_2_attack_count=DD_ATTACK_COUNT[player_2_engagement_form],0<player_2_attack_count?(player_2_turn_counter+=1,attackMain()):(player_2_turn_counter+=
1,nextPlayer())):player_1_turn_counter<player_1_ships_count[SHIP_CLASS_DD]+player_1_ships_count[SHIP_CLASS_CA]+player_1_ships_count[SHIP_CLASS_BB]?nextPlayer():player_2_turn_counter<player_2_ships_count[SHIP_CLASS_CV]+player_2_ships_count[SHIP_CLASS_DD]+player_2_ships_count[SHIP_CLASS_CA]+player_2_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_CV,player_2_attack_count=CV_ATTACK_COUNT[player_2_engagement_form],0<player_2_attack_count&&(player_2_turn_counter+=1,attackMain())):nextPlayer()));
break;case GAME_MODE_CLASSIC:0<getPlayerShipCount(PLAYER_2)&&(player_2_attack_count=1),0<player_2_attack_count?(player_2_turn_counter+=1,attackMain()):nextPlayer()}else switch(hideActionPrompt(),acting_player=PLAYER_1,game_mode){case GAME_MODE_SKIRMISH:case GAME_MODE_INTERCEPT:case GAME_MODE_CONVOY:case GAME_MODE_BREAKTHROUGH:game_phase==GAME_PAHSE_AERIAL_COMBAT?(player_2_acted=!0,player_1_attack_count=2*player_1_ships_count[SHIP_CLASS_CV],0<player_1_attack_count&&!player_1_acted?beginTargeting():
startFleetCombat()):game_phase==GAME_PHASE_COMBAT&&(player_1_first_act_complete?(player_1_turn_counter<=player_1_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_BB,player_1_attack_count=BB_ATTACK_COUNT[player_1_engagement_form]):player_1_turn_counter<=player_1_ships_count[SHIP_CLASS_CA]+player_1_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_CA,player_1_attack_count=CA_ATTACK_COUNT[player_1_engagement_form]):player_1_turn_counter<=player_1_ships_count[SHIP_CLASS_DD]+player_1_ships_count[SHIP_CLASS_CA]+
player_1_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_DD,player_1_attack_count=DD_ATTACK_COUNT[player_1_engagement_form]):player_1_turn_counter<=player_1_ships_count[SHIP_CLASS_CV]+player_1_ships_count[SHIP_CLASS_DD]+player_1_ships_count[SHIP_CLASS_CA]+player_1_ships_count[SHIP_CLASS_BB]&&(ship_class_acting=SHIP_CLASS_CV,player_1_attack_count=CV_ATTACK_COUNT[player_1_engagement_form]),player_1_turn_counter+=1,player_1_turn_counter>getPlayerShipCount(PLAYER_1)-player_1_ships_count[SHIP_CLASS_AP]&&
(player_1_acted=!0),player_2_acted&&player_1_acted&&(player_1_turn_counter=player_2_turn_counter=0,total_turn_counter+=1,game_mode!=GAME_MODE_INTERCEPT&&game_mode!=GAME_MODE_CONVOY&&game_mode!=GAME_MODE_BREAKTHROUGH||updateTurnCounter(),player_1_acted=player_2_acted=!1),0<player_1_attack_count?beginTargeting():nextPlayer()):(player_1_turn_counter>=getPlayerShipCount(PLAYER_1)-player_1_ships_count[SHIP_CLASS_AP]&&(player_1_first_act_complete=!0),player_1_turn_counter<player_1_ships_count[SHIP_CLASS_BB]?
(ship_class_acting=SHIP_CLASS_BB,player_1_attack_count=BB_ATTACK_COUNT[player_1_engagement_form],0<player_1_attack_count&&(player_1_turn_counter+=1,beginTargeting())):player_2_turn_counter<player_2_ships_count[SHIP_CLASS_BB]?nextPlayer():player_1_turn_counter<player_1_ships_count[SHIP_CLASS_CA]+player_1_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_CA,player_1_attack_count=CA_ATTACK_COUNT[player_1_engagement_form],0<player_1_attack_count?(player_1_turn_counter+=1,beginTargeting()):(player_1_turn_counter+=
1,nextPlayer())):player_2_turn_counter<player_2_ships_count[SHIP_CLASS_CA]+player_2_ships_count[SHIP_CLASS_BB]?nextPlayer():player_1_turn_counter<player_1_ships_count[SHIP_CLASS_DD]+player_1_ships_count[SHIP_CLASS_CA]+player_1_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_DD,player_1_attack_count=DD_ATTACK_COUNT[player_1_engagement_form],0<player_1_attack_count?(player_1_turn_counter+=1,beginTargeting()):(player_1_turn_counter+=1,nextPlayer())):player_2_turn_counter<player_2_ships_count[SHIP_CLASS_DD]+
player_2_ships_count[SHIP_CLASS_CA]+player_2_ships_count[SHIP_CLASS_BB]?nextPlayer():player_1_turn_counter<player_1_ships_count[SHIP_CLASS_CV]+player_1_ships_count[SHIP_CLASS_DD]+player_1_ships_count[SHIP_CLASS_CA]+player_1_ships_count[SHIP_CLASS_BB]?(ship_class_acting=SHIP_CLASS_CV,player_1_attack_count=CV_ATTACK_COUNT[player_1_engagement_form],0<player_1_attack_count&&(player_1_turn_counter+=1,beginTargeting())):nextPlayer()));break;case GAME_MODE_CLASSIC:0<getPlayerShipCount(PLAYER_1)&&(player_1_attack_count=
1),0<player_1_attack_count?(player_1_turn_counter+=1,beginTargeting()):nextPlayer()}}function updateTurnCounter(){document.getElementById("TurnCounter").innerHTML=max_turn_intercept_breakthrough-total_turn_counter}
function gameEnded(){if(0>=getPlayerShipCount(PLAYER_1))return showEndGameDialog(string.defeat,string.defeat_description_standard),!0;if(0>=getPlayerShipCount(PLAYER_2))return showEndGameDialog(string.victory,string.victory_description_standard),!0;if(game_mode==GAME_MODE_INTERCEPT){if(total_turn_counter>=max_turn_intercept_breakthrough)return showEndGameDialog(string.defeat,string.defeat_description_intercept),!0;if(SPECIFIC_CLASS_INTERCEPT_BREAKTHROUGH&&0>=player_2_ships_count[ship_class_target])return showEndGameDialog(string.victory,
string.victory_description_intercept),!0}else if(game_mode==GAME_MODE_BREAKTHROUGH){if(total_turn_counter>=max_turn_intercept_breakthrough)return showEndGameDialog(string.victory,string.victory_description_breakthrough),!0;if(SPECIFIC_CLASS_INTERCEPT_BREAKTHROUGH&&0>=player_1_ships_count[ship_class_target])return showEndGameDialog(string.defeat,string.defeat_description_breakthrough),!0}else if(game_mode==GAME_MODE_CONVOY){if(total_turn_counter>=max_turn_intercept_breakthrough)return showEndGameDialog(string.victory,
string.victory_description_convoy),!0;if(0>=player_1_ships_count[SHIP_CLASS_AP])return showEndGameDialog(string.defeat,string.defeat_description_convoy),!0}else return!1}function showEndGameDialog(a,b){document.getElementById("EndingTitle").innerHTML=a;document.getElementById("EndingDescription").innerHTML=b;document.getElementById("endGameBox").style.display="table";setTimeout(function(){window.onclick=function(a){document.getElementById("endGameBox").style.display="none"}},3E3)}
function surrender(a){if(confirm(string.surrender_confirm)){for(a=0;a<player_1_ships_count.length;a++)player_1_ships_count[a]=0;nextPlayer()}}function newGame(a){confirm(string.new_game_confirm)&&location.reload()};
